### ISSUE TITLE
Enhancement of Error Message (Ipython)

### ISSUE THREAD

**Issue by kirankotari** [NSO-developer/ncs_pycli#13]
IPython dependency was missing but it shows ipy variable issue. 
```
[ ERROR ] :: [ ncs_pycli ] :: no module ipython found..!
[ INFO ] :: [ ncs_pycli ] :: you can install via pip "pip install ipython"
Traceback (most recent call last):
  File "/home/xxxxx/python/ncs_cli/venv/bin/ncs_pycli", line 8, in <module>
    sys.exit(run())
  File "/home/xxxxx/python/ncs_cli/venv/lib/python3.9/site-packages/ncs_pycli/ncs_pycli.py", line 150, in run
    obj.initialize(sys.argv)
  File "/home/xxxxx/python/ncs_cli/venv/lib/python3.9/site-packages/ncs_pycli/ncs_pycli.py", line 105, in initialize
    shell = self._get_shell()
  File "/home/xxxxx/python/ncs_cli/venv/lib/python3.9/site-packages/ncs_pycli/ncs_pycli.py", line 92, in _get_shell
    if ipy.get_ipython() is None:
NameError: name 'ipy' is not defined
```

Expected:
Looks like an issue with IPython, can you run `ipython` command, we are expecting as following
```
Python 3.9.13 (main, Oct 10 2022, 21:05:14)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
```

**Comment by JohanVikman** [comment]
Looks like ipython was not installed in your virtual environment.  Reading from the top you can see:
 
[ ERROR ] :: [ ncs_pycli ] :: no module ipython found..!
[ INFO ] :: [ ncs_pycli ] :: you can install via pip "pip install ipython"

**Comment by JohanVikman** [comment]
You can still start iPython even though it's not installed in your virtualenv because you have it in your path and ipython isn't aware of the virtual environment.
